### ISSUE TITLE
[BUG] Neptune_ML widget error in 2.0.9

### ISSUE THREAD

**Issue by bechbd** [aws/graph-notebook#81] opened 2021-03-12 00:36 UTC
**Describe the bug**
Starting in version 2.0.9 the neptune_ml widget is having an issue where the json values being passed in are getting the following error 
```
{'error': JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)}
```

**To Reproduce**
1. Run through the 01-Introduction-to-Node-Classification-Gremlin notebook
2. When you get to the export step the error occurs

**Additional context**
This is not a problem in version 2.0.7

**Comment by bechbd** [comment] 2021-03-17 16:58
This appears to be an issue with the versions of `ipython` that SageMaker is using.  If you update the Lifecycle start script by putting the following code at the bottom (just before EOF) and stopping and starting the notebook.
```
source activate JupyterSystemEnv
pip install --upgrade ipython==7.16.1
source /home/ec2-user/anaconda3/bin/deactivate
```

**Comment by Kristof-Neys** [comment] 2021-04-05 17:06
Hi, i have updated the Lifecycle scripts as suggested:

#!/bin/bash
sudo -u ec2-user -i <<'EOF'

echo "export GRAPH_NOTEBOOK_AUTH_MODE=DEFAULT" >> ~/.bashrc
echo "export GRAPH_NOTEBOOK_IAM_PROVIDER=ROLE" >> ~/.bashrc
echo "export GRAPH_NOTEBOOK_SSL=True" >> ~/.bashrc
echo "export GRAPH_NOTEBOOK_HOST=neptunedbcluster-lolvzvcvwqgd.cluster-cqqsvgvoyzlx.us-east-1.neptune.amazonaws.com" >> ~/.bashrc
echo "export GRAPH_NOTEBOOK_PORT=8182" >> ~/.bashrc
echo "export NEPTUNE_LOAD_FROM_S3_ROLE_ARN=arn:aws:iam::504028651370:role/neptuneml-NeptuneBaseStack-Y-NeptuneLoadFromS3Role-1UBUI982ZI077" >> ~/.bashrc
echo "export AWS_REGION=us-east-1" >> ~/.bashrc

echo "export NEPTUNE_ML_ROLE_ARN=arn:aws:iam::504028651370:role/neptuneml-NeptunMLCoreStack-2OGKH-NeptuneMLIAMRole-U8Y193MBESPX" >> ~/.bashrc

echo "export NEPTUNE_EXPORT_API_URI=https://wvxk88hzea.execute-api.us-east-1.amazonaws.com/v1/neptune-export" >> ~/.bashrc

aws s3 cp s3://aws-neptune-notebook/graph_notebook.tar.gz /tmp/graph_notebook.tar.gz
rm -rf /tmp/graph_notebook
tar -zxvf /tmp/graph_notebook.tar.gz -C /tmp
/tmp/graph_notebook/install.sh

aws s3 cp --recursive s3://aws-neptune-customer-samples/v2/notebooks/ ~/SageMaker/Neptune 
chmod -R a+rw ~/SageMaker/Neptune/*

source activate JupyterSystemEnv
pip install --upgrade ipython==7.16.1
source /home/ec2-user/anaconda3/bin/deactivate


EOF



but still getting the same error: 
{'error': JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)}

can you help or suggest other workaround? 

thanks

**Comment by austinkline** [comment] 2021-04-05 19:32
Hi @Kristof-Neys, can you give a screenshot of the error so we can confirm/reproduce?

**Comment by Kristof-Neys** [comment] 2021-04-06 11:40
> Hi @Kristof-Neys, can you give a screenshot of the error so we can confirm/reproduce?


<img width="1103" alt="error_train_screen" src="https://user-images.githubusercontent.com/10049871/113705359-4123d580-96d5-11eb-9b65-59e38f3e5140.png">

**Comment by Kristof-Neys** [comment] 2021-04-06 11:41
> > Hi @Kristof-Neys, can you give a screenshot of the error so we can confirm/reproduce?
> 
> <img alt="error_train_screen" width="1103" src="https://user-images.githubusercontent.com/10049871/113705359-4123d580-96d5-11eb-9b65-59e38f3e5140.png">

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/10049871/113705546-73cdce00-96d5-11eb-81fa-633c14942847.png">

**Comment by Kristof-Neys** [comment] 2021-04-06 11:44
> Hi @Kristof-Neys, can you give a screenshot of the error so we can confirm/reproduce?

hi @austinkline  - thanks for helping me out. So as you can see from the screenshots, it fails to download the data and seems to be adding a backslash... 

AWS and certainly Neptune is all new to me, so any help & workaround you can give me is very much appreciated!

**Comment by austinkline** [comment] 2021-04-06 16:17
Thanks for the info, glad you have a workaround while we reproduce. I'll spend some time reproducing and get back to you

**Comment by austinkline** [comment] 2021-04-06 17:43
I was not able to reproduce this issue after running a fresh notebook created via cloud-formation found in our public docs

![image](https://user-images.githubusercontent.com/8711160/113755017-afac6780-96c4-11eb-86ee-42798d595609.png)

@Kristof-Neys I wonder if the state of the notebook got mixed up somehow? I would suggest creating a fresh notebook instance and trying again. The bug which needed the workaround lifecycle configuration has been resolved and released to pypi so that is not needed anymore

**Comment by Kristof-Neys** [comment] 2021-04-07 16:39
> I was not able to reproduce this issue after running a fresh notebook created via cloud-formation found in our public docs
> 
> ![image](https://user-images.githubusercontent.com/8711160/113755017-afac6780-96c4-11eb-86ee-42798d595609.png)
> 
> @Kristof-Neys I wonder if the state of the notebook got mixed up somehow? I would suggest creating a fresh notebook instance and trying again. The bug which needed the workaround lifecycle configuration has been resolved and released to pypi so that is not needed anymore

thank you @austinkline . I'll re-run everything from fresh... - meanwhile, how can I figure out which GNN model is actually used and the model specifics in DGL?

**Comment by austinkline** [comment] 2021-04-07 17:30
> thank you @austinkline . I'll re-run everything from fresh... - meanwhile, how can I figure out which GNN model is actually used and the model specifics in DGL?

Checked with the team about this, you should be able to find this information in cloudwatch logs for that particular job in the Sagemaker console.

**Comment by Kristof-Neys** [comment] 2021-04-07 17:43
> > thank you @austinkline . I'll re-run everything from fresh... - meanwhile, how can I figure out which GNN model is actually used and the model specifics in DGL?
> 
> Checked with the team about this, you should be able to find this information in cloudwatch logs for that particular job in the Sagemaker console.

yeah thanks - just found it in the S3, says rgcn which presumably stands for the relational graph convolutional network

**Comment by sojiadeshina** [comment] 2021-04-07 17:54
> > > thank you @austinkline . I'll re-run everything from fresh... - meanwhile, how can I figure out which GNN model is actually used and the model specifics in DGL?
> > 
> > 
> > Checked with the team about this, you should be able to find this information in cloudwatch logs for that particular job in the Sagemaker console.
> 
> yeah thanks - just found it in the S3, says rgcn which presumably stands for the relational graph convolutional network

yes. that's correct.

**Comment by austinkline** [comment] 2021-04-13 14:48
Hi @Kristof-Neys and updates? Did recreating work for you?

**Comment by Kristof-Neys** [comment] 2021-04-13 15:52
Hi @austinkline - thanks for reaching out. I have been caught up in another project but was just about to look at it. I'll update you guys probably tomorrow.

**Comment by Kristof-Neys** [comment] 2021-04-21 08:54
hi @austinkline & Team, i am finally getting around to this. I started everything new but now I cannot export the configuration any more, I get the following error:
`{'error': ConnectionError(MaxRetryError("HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: /neptune-export (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f28f5e81748>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),)}`

any ideas? Thanks!!

**Comment by austinkline** [comment] 2021-04-22 00:30
Let's start by gathering what version you're running again and what your configuration looks like. What we want to figure out is whether the exporter or Neptune is throwing the exception provided. That is to say, was the exporter unable to be called due to a missing auth token, or did the exporter start and then it was unable to communicate with Neptune. You also could take a look at cloudwatch logs for your api gateway on the corresponding exporter resource and see if it has any additional info you can point to. I'll go ahead and provision a fresh stack and see if I get the same issue once we've confirmed your auth setting.

Can you provide your notebook version and configuration by running the following:

1. What cell did you execute that gave you the above mentioned error?

2. What version of `graph-notebook` are you running?
```
%graph_notebook_version
```

3. What is your configuration? Really we just care about the authentication setting
**NOTE: PLEASE ERASE OR BLOCK OUT YOUR HOST ENDPOINT FROM YOUR CONFIGURATION WHEN PROVIDING THIS INFO**

```
%graph_notebook_config
```

**Comment by Kristof-Neys** [comment] 2021-04-22 11:02
> Let's start by gathering what version you're running again and what your configuration looks like. What we want to figure out is whether the exporter or Neptune is throwing the exception provided. That is to say, was the exporter unable to be called due to a missing auth token, or did the exporter start and then it was unable to communicate with Neptune. You also could take a look at cloudwatch logs for your api gateway on the corresponding exporter resource and see if it has any additional info you can point to. I'll go ahead and provision a fresh stack and see if I get the same issue once we've confirmed your auth setting.
> 
> Can you provide your notebook version and configuration by running the following:
> 
>     1. What cell did you execute that gave you the above mentioned error?
> 
>     2. What version of `graph-notebook` are you running?
> 
> 
> ```
> %graph_notebook_version
> ```
> 
>     1. What is your configuration? Really we just care about the authentication setting
>        **NOTE: PLEASE ERASE OR BLOCK OUT YOUR HOST ENDPOINT FROM YOUR CONFIGURATION WHEN PROVIDING THIS INFO**
> 
> 
> ```
> %graph_notebook_config
> ```

@austinkline thank you! Very much appreciate taking time & effort. Ok, so these are the detail:

cell that I am running:
`%%neptune_ml export start --export-url {neptune_ml.get_export_service_host()} --export-iam --wait --store-to export_results
${export_params}`
=> this gives me error: 
`{
  "message": "Missing Authentication Token"
}`


Version graph-notebook: 2.1.0

%graph_notebook_config:
`{
  "host": "neptunedbcluster-xxxxxx.....xxxxxx.us-east-1.neptune.amazonaws.com",
  "port": 8182,
  "auth_mode": "DEFAULT",
  "load_from_s3_arn": "arn:aws:iam::504028651370:role/neptuneml-NeptuneBaseStack-Y-NeptuneLoadFromS3Role-1UBUI982ZI077",
  "ssl": true,
  "aws_region": "us-east-1",
  "sparql": {
    "path": "sparql"
  }
}`

The strange thing is that all worked well two weeks ago, altho I did get wrong predictions, but at least the export worked and I could train model and get predictions etc. Now I cannot get beyond the export.... 

thank you again

**Comment by austinkline** [comment] 2021-04-22 15:49
@Kristof-Neys I believe I found the bug we're dealing with. Can you flip IAM auth on in your config and see if the exporter/other components work?

```
%%graph_notebook_config
{
  "host": "neptunedbcluster-xxxxxx.....xxxxxx.us-east-1.neptune.amazonaws.com",
  "port": 8182,
  "auth_mode": "IAM",
  "load_from_s3_arn": "arn:aws:iam::504028651370:role/neptuneml-NeptuneBaseStack-Y-NeptuneLoadFromS3Role-1UBUI982ZI077",
  "ssl": true,
  "aws_region": "us-east-1",
  "sparql": {
    "path": "sparql"
  }
}
```

Note that we're changing the auth mode to IAM

**Comment by Kristof-Neys** [comment] 2021-04-23 11:57
> @Kristof-Neys I believe I found the bug we're dealing with. Can you flip IAM auth on in your config and see if the exporter/other components work?
> 
> ```
> %%graph_notebook_config
> {
>   "host": "neptunedbcluster-xxxxxx.....xxxxxx.us-east-1.neptune.amazonaws.com",
>   "port": 8182,
>   "auth_mode": "IAM",
>   "load_from_s3_arn": "arn:aws:iam::504028651370:role/neptuneml-NeptuneBaseStack-Y-NeptuneLoadFromS3Role-1UBUI982ZI077",
>   "ssl": true,
>   "aws_region": "us-east-1",
>   "sparql": {
>     "path": "sparql"
>   }
> }
> ```
> 
> Note that we're changing the auth mode to IAM
hey @austinkline  - that worked!, export and training went fine....but still predicting the wrong genre.... - how can this be??

<img width="904" alt="image" src="https://user-images.githubusercontent.com/10049871/115867858-82d1b180-a433-11eb-809c-a1aa733e5d90.png">

**Comment by bechbd** [comment] 2021-04-23 16:38
@Kristof-Neys The issue you are seeing is actually one where the text in the notebook is incorrect.  Drama is what is coming back from the model that is generated .  I have created an issue to track this https://github.com/aws/graph-notebook/issues/116 and will address this with the additional feedback on those notebooks in the near future.

**Comment by Kristof-Neys** [comment] 2021-04-28 16:01
> @Kristof-Neys The issue you are seeing is actually one where the text in the notebook is incorrect. Drama is what is coming back from the model that is generated . I have created an issue to track this #116 and will address this with the additional feedback on those notebooks in the near future.

ok understood - thank you

**Comment by austinkline** [comment] 2021-05-06 19:49
Closing this out since we're tracking the reported issue of notebooks being out of date in #116. Please cut us a new ticket if you run into any further issues!

**Closed by austinkline** 2021-05-06 19:49 UTC
Labels: bug

**Comment by llealgt** [comment] 2023-02-10 21:57
Hi guys, I'm facing a similar issue, I applied your fix(setting "auth_mode": "IAM") but did not work, any suggestions?

**Comment by michaelnchin** [comment] 2023-02-11 01:31
Hi @llealgt , is this referring to the same issue mentioned at https://github.com/aws/graph-notebook/issues/445#issuecomment-1426192856?

**Comment by llealgt** [comment] 2023-02-13 18:48
Hi @michaelnchin, nope, it's not the same, this happens when running notebook 
Neptune-ML-01-Introduction-to-Node-Classification-Gremlin
The other errors happen in notebook 
Neptune-ML-00-Getting-Started-with-Neptune-ML-Gremlin
I guess it is related but they are different errors in different notebooks.
