### ISSUE TITLE
[BUG] %db_reset command throwing error

### ISSUE THREAD

**Issue by bechbd** [aws/graph-notebook#122] opened 2021-05-06 00:12 UTC
**Describe the bug**
I am getting an error from Jupyter when running the `%db_reset` command.  I do not know if it matters, but this is a rather large db that is being dropped, and I have not seen this on smaller DBs.

**To Reproduce**
Run a `%db_reset` command

![image](https://user-images.githubusercontent.com/6898505/117224432-63843e00-adbc-11eb-892c-0982597f1773.png)

**Comment by michaelnchin** [comment] 2022-10-29 01:06
#368 is a duplicate of this, bug was fixed in #369. Resolving.

**Closed by michaelnchin** 2022-10-29 01:06 UTC
Labels: bug
