### ISSUE TITLE
Limit issue .with("Neptune#ml.limit",3)

### ISSUE THREAD

**Issue by Roshin29** [aws/graph-notebook#144] opened 2021-07-22 00:16 UTC
Hi

As per the below code It is allowing only default limit as 1 and the limit 3 is not working and throwing error for Introduction to Node Classification Gremlin

%%gremlin
g.with("Neptune#ml.endpoint","node-cla-2021-07-15-15-13-940000-endpoint").with( "Neptune#ml.limit", 3 ).V().has('title', 'Toy Story (1995)').properties("genre").with("Neptune#ml.classification").value()

Error
{
  "requestId": "fbab9b0a-176c-47f8-accc-969fc4580792",
  "detailedMessage": "Incompatible data from external service. Please check your service configuration and query again.",
  "code": "ConstraintViolationException"
}

Can some one suggest is there something wrong with the code which was mentioned in the document

**Comment by michaelnchin** [comment] 2021-09-29 23:20
Hi @Roshin29, thank you for the bug report! 

The machine learning sample notebooks received substantial revisions in [Release 3.0.1](https://github.com/aws/graph-notebook/releases/tag/v3.0.1). This release also included a number of changes under the hood to support the general availability release of Amazon Neptune ML.

The Gremlin query listed is only seen in older versions of the `Neptune-ML-01-Introduction-to-Node-Classification-Gremlin` sample notebook, and is now replaced by the one below:
```
%%gremlin
g.with("Neptune#ml.endpoint","${endpoint}").
  with("Neptune#ml.limit",3).
  V().has('title', 'Apollo 13 (1995)').properties("genre").with("Neptune#ml.classification").value()

```
I am not able to reproduce the listed exception when running this query using graph-notebook v3.0.6, so the issue appears to have been resolved with the latest changes.

Closing this issue out, as there are no further action items at this time. Please feel free to re-open if you have any further questions.

**Closed by michaelnchin** 2021-09-29 23:20 UTC
Labels: bug
