### ISSUE TITLE
[BUG] Gremlin magics stopped working after upgrade to 1.2.0.2 cluster version

### ISSUE THREAD

**Issue by donatoaz** [aws/graph-notebook#401] opened 2022-11-29 14:48 UTC
**Describe the bug**

Some gremlin magics stopped working after upgrading cluster to 1.2.0.2.

**To Reproduce**
1. Upgrade cluster to 1.2.0.2
2. On a notebook attempt to create a `dataprocessing`, `training` or `endpoint` from a notebook using `%neptune_ml` magics **with `--wait`** flag
4. See error when it tries to request status

```
Wait called on dataprocessing job link-prediction-1669731562

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/graph_notebook/magics/ml.py in wait_for_dataprocessing(job_id, client, output, wait_interval, wait_timeout)
    421             update_status_output.clear_output()
    422             status_res = client.dataprocessing_job_status(job_id)
--> 423             status_res.raise_for_status()
    424             status = status_res.json()
    425             if status['status'] in ['Completed', 'Failed']:

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
   1019 
   1020         if http_error_msg:
-> 1021             raise HTTPError(http_error_msg, response=self)
   1022 
   1023     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://mycluster-xxx.us-east-1.neptune.amazonaws.com:8182/ml/dataprocessing/link-prediction-1669731562

None

```

**Expected behavior**

The status call made because of the `--wait` flag should work.

**Screenshots**

![neptune-error](https://user-images.githubusercontent.com/127527/204559695-74436f6d-fe9f-4adb-9aa8-0d5e49d68547.png)

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser: firefox
 - Version: 106.0.5 (64-bit)

**Additional context**

It seems the correct endpoint to be requesting statuses is:

```
https://<host>:8182/ml/dataprocessing?id=<jobId>
```

instead of

```
https://<host>:8182/ml/dataprocessing/<jobId>
```

as is on `src/graph_notebook/neptune/client.py`

**Comment by michaelnchin** [comment] 2023-01-03 22:22
Bug is not reproducible internally on Neptune engine version 1.2.0.2. Closing until we have more information on a possible root cause.

**Closed by michaelnchin** 2023-01-03 22:22 UTC
Labels: bug
